name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project and development dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov ruff mypy pip-audit

      - name: Lint code with ruff
        run: |
          ruff travel_perks tests

      - name: Type check with mypy
        run: |
          mypy travel_perks

      - name: Run tests with coverage (fail under 85%)
        run: |
          pytest --cov=travel_perks --cov-report=term-missing --cov-fail-under=85

      - name: Audit dependencies
        run: |
          pip-audit

  build-container:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t travel_perks:latest .